# action.yml
name: 'Compile LateX'
description: 'Compile Latex/XeLatex files easily !'
branding:
  icon: file-text
  color: blue
inputs:
  tex_path:  # id of input
    description: 'Path of Tex File'
    required: true
  push:
    description: 'String stating whether to push output PDF, PDF will only be pushed in case of "yes"'
    default: 'no'
    required: false
  link_tectonic_cache:
    description: 'Link docker tectonic cache to github cache'
    default: 'no'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tex_path }}
    - ${{ inputs.push }}
    - ${{ inputs.link_tectonic_cache }}
